[Printing]
# Input press sheets will be cut in the x and y axis by these factors and
# added to possible sheet sizes. Leave blank for no prepress cutting.
prepress_cutting_factors = 2,3,4,5 

sheets_per_unit_pantone  = 750000
sheets_per_unit_metallic = 450000

# Percent ink coverage.
default_coverage = 25

# The amount of material (in inches) around the screen 'plate' needed to
# stretch over the frame.
screen_lap = 6

[Docket]
display_time_data = 1


[Imposition]
bound_x = 82
bound_y = 82

web_colour_bar_size = 0.45
std_colour_bar_size = 0.75

# Ammount of trim off for bindery types
trim_stitching = 0.000
trim_perfect   = 0.000
trim_spiral    = 0.000


[Scoring]
always_score_covers = 0

# The maximum stock calliper that can be folded without needing scoring.
max_calliper_uncoated = 0.007
max_calliper_coated   = 0.007


[Folding]
# Default gap between sheets in inches if none provided for equipment.
default_gap = 2


[Padding]
# Backing material to use, string ID must exist in material table.
backing_material = 24PTBoard


[Packing]
max_weight_carton = 40
max_weight_skid   = 1500


[Shipping]
min_ship_weight = 5

# Number of samples shipped when 'ship samples' chosen (for weight).
number_of_samples = 5

# Weight to use for each square inch of proof when shipping proofs (based on
# 100lbs Text).
pounds_per_proof_inch = 0.000210714

[General]
# Search and Replace on html. old,new spelling ( no spaces between comma )
word_sub = colour,colour,Colour,Colour
